jwt:
  secret-key: ${JWTKEY}
  token:
    expired-time-ms: 1800000

spring:
  datasource:
    url: ${DBURL}
    username: ${DBUSER}
    password: ${DBPW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: ${MAILPORT}
    username: ${MAILUSER}
    password: ${MAILPW}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000



logging:
  level:
    org.springframework.security: DEBUG

cloud:
  aws:
    s3:
      bucket: ${S3BUCKETNAME}
    credentials:
      access-key: ${S3ACCESSKEY}
      secret-key: ${S3SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

message:
  set:
    from: ${MESSAGEUSER}
    text: ${MESSAGETEXT}
    subject1: ${MESSAGESUB1}
    subject2: ${MEGGAGESUB2}
    subject3: ${MESSAGESUB3}

portone:
  imp_key: ${PORTKEY}
  imp_secret: ${PORTSECRET}

opentracing:
  jaeger:
    service-name: test-svc
    udp-sender:
      host: ${SENDERHOST}
      port: ${SENDERPORT}